### ISSUE TITLE
Transparent Huge Pages (THP) warning

### ISSUE THREAD

**Issue by malte-behrendt-gr** [OT-CONTAINER-KIT/redis#1]
When deploying this docker image (via Redis Operator - thanks for that one!) I get a warning:

`WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.`

Is there a way to configure it/set THP settings by default?

**Comment by iamabhishek-dubey** [comment]
This more like a kernel setting, I would suggest handling this change on the node itself
