### ISSUE TITLE
Push TLS enable image to quay.io

### ISSUE THREAD

**Issue by hufon** [OT-CONTAINER-KIT/redis#10]
When the TLS enabled image would be pushed on quay.io ?

**Comment by drivebyer** [comment]
It seems be done, see https://github.com/OT-CONTAINER-KIT/redis/blob/3cbab7113485b3671ca18e0f85475570592dd4cc/Dockerfile#L20 @hufon

**Comment by shubham-cmyk** [comment]
Yes we already have TLS enabled in the redis 

@hufon can you be more specific what is your query? 
https://github.com/OT-CONTAINER-KIT/redis/blob/master/entrypoint.sh#L52
