### ISSUE TITLE
[BUG] upgrading from v6.2.5 to v7.0.5 with persistence issue

### ISSUE THREAD

**Issue by atalakey4work** [OT-CONTAINER-KIT/redis#21]
Due to the group id and user id change from 1001 to 1000 that was done when redis was upgraded from v6.2.5 to v7.0.5, upgrading resid with persistence throws the below error:

Can't open or create append-only dir appendonlydir: Permission denied

https://github.com/OT-CONTAINER-KIT/redis/commit/fac6855936ab3f0dd74bf1c4247874598cfd27ce#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R33

**Comment by shubham-cmyk** [comment]
You can change the user and group by security context in k8s which we already provide in the redis-cluster
