### ISSUE TITLE
Push updated images to Quay.io

### ISSUE THREAD

**Issue by Bengrunt** [OT-CONTAINER-KIT/redis#31]
Hello,

I'm using your Redis operator (v0.14.0) on Openshift/OKD clusters and I realized that the default image (ie. `quay.io/opstree/redis:v7.0.5`) used by the operator and helm charts was built several months ago (November 2022). As such, it does not contain latest bug fixes from the newest Redis releases, nor the most needed write permission fix that would allow proper deployment on Openshift clusters without having to lower security (see https://github.com/OT-CONTAINER-KIT/redis/pull/28).

I know I can build it myself but I believe that it would be a smoother on-boarding experience if working images were provided by default to the users of your Redis operator.

Thanks a lot for what you're doing.

**Comment by shubham-cmyk** [comment]
Added a workflow that would push the the latest redis image under `latest` tag of opstree redis image. 
Use : `quay.io/opstree/redis:latest `for the latest redis images

**Comment by Bengrunt** [comment]
Thanks a lot!
However, it looks like the push to the quay.io registry failed in Github actions.

**Comment by shubham-cmyk** [comment]
It failed becuause I was not granted the access to make changes of that repo, I have asked access with my team. I would re run test as soon I get it

**Comment by shubham-cmyk** [comment]
Pushed now

**Comment by Bengrunt** [comment]
Thank you so much !
