### ISSUE TITLE
Lack of persistency in /node-conf  path

### ISSUE THREAD

**Issue by guychekarev** [OT-CONTAINER-KIT/redis#34]
Hi, 
Starting from this change ([7459d11](https://github.com/OT-CONTAINER-KIT/redis/commit/7459d119085e0f0ba6ba91f92ccfcf22555eb935)) we have been facing issues with node configuration consistency. 
Followers failed to reconnect back to the cluster once their pod had been replaced. The followers couldn't find the node configuration since it did not persist after the restart. 
As a temporary fix we moved the `/node-conf` into `/data`, which fixed the issue since `/data` was a mounted volume.

Kind Regards,
Guy

**Comment by shubham-cmyk** [comment]
I think this should not be the case since the object to add this was to make the pod more stable my moving the cluster configuration into a persistent volume. 

Can you elaborate more this needs to be fixed.

**Comment by guychekarev** [comment]
@shubham-cmyk Thanks for your response. As I understand you were meaning to put `/node-conf` on a dedicated PVC, but in the Dockerfile the only volume was `/data`.
https://github.com/OT-CONTAINER-KIT/redis/blob/f00884e30ed6e300f5161ea001ace631c24f19f7/Dockerfile#L50

**Comment by shubham-cmyk** [comment]
@guychekarev 
I just mounted the volume of the pod at location `/node-conf` to a PVC.  
This could make the sure that `node.conf` is not lost but I am not sure on the container restart. 

I think you can open a PR that could add another VOLUME["/node-conf"] 

Let's see whether that could solve the problem
