### ISSUE TITLE
[Bug] : Wrong Config File in ACL mode

### ISSUE THREAD

**Issue by shubham-cmyk** [OT-CONTAINER-KIT/redis#37]
It should be `sentinel.conf` not the `redis.conf` over here :https://github.com/OT-CONTAINER-KIT/redis/pull/35/files#diff-c3c0dcf3892b7d0c37d75bd5bf1865954c6839821f93b27c7083f9cd97011eb6R66

**Comment by Akshaykumar05** [comment]
Hi @shubham-cmyk 
Let me fix this issue.
