### ISSUE TITLE
Multi arch image support

### ISSUE THREAD

**Issue by boedy** [OT-CONTAINER-KIT/redis#43]
The operator now seems to have multi arch image support (https://github.com/OT-CONTAINER-KIT/redis-operator/issues/564), but the redis images currently don't work on arm64. Would love to see arm64 support through Multi arch images.

**Comment by shubham-cmyk** [comment]
This is already fixed. But The images are not pushed. 

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/.github/workflows/release-images.yaml

**Comment by shubham-cmyk** [comment]
We try to build multi arch image : 

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/.github/workflows/release-images.yaml#L33

**Comment by drivebyer** [comment]
> We try to build multi arch image :
> 
> https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/.github/workflows/release-images.yaml#L33

But it seem for operator, not for redis

**Comment by shubham-cmyk** [comment]
> > We try to build multi arch image :
> > 
> > https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/.github/workflows/release-images.yaml#L33
> 
> But it seem for operator, not for redis

We could do same for redis as well.
