### ISSUE TITLE
redis 6.2 add a new feature: disable-thp

### ISSUE THREAD

**Issue by Unknown256** [OT-CONTAINER-KIT/redis#5]
#################### KERNEL transparent hugepage CONTROL ######################

# Usually the kernel Transparent Huge Pages control is set to "madvise" or
# or "never" by default (/sys/kernel/mm/transparent_hugepage/enabled), in which
# case this config has no effect. On systems in which it is set to "always",
# redis will attempt to disable it specifically for the redis process in order
# to avoid latency problems specifically with fork(2) and CoW.
# If for some reason you prefer to keep it enabled, you can set this config to
# "no" and the kernel global to "always".

disable-thp yes

It's very useful

**Comment by iamabhishek-dubey** [comment]
I think this can be externalized now with external config
