### ISSUE TITLE
Add explicit version tag to latest images

### ISSUE THREAD

**Issue by solipsistadventurer** [OT-CONTAINER-KIT/redis#74]
Currently, the redis, redis-exporter and redis-sentinel images that are pushed to quay.io do not have a corresponding tag with the explicit version.
We prefer to be able to refer to a specific to avoid unintended upgrades when a new version is published.
Please tag your images with the explicit version number, in addition to the 'latest' tag.

**Comment by drivebyer** [comment]
Thank you for your feedback. It has been addressed. We push versions 6.2.14 and 7.0.15 with every master branch update.
