### ISSUE TITLE
BUG: Entrypoint sentinel with TLS enabled bug

### ISSUE THREAD

**Issue by Leo791** [OT-CONTAINER-KIT/redis#80]
I noticed that the port setup for sentinel is being done like so:

```
port_setup() {
        {
            echo port "${SENTINEL_PORT}"
        } >> /etc/redis/sentinel.conf
}
```

And the port and tls_port are being defined in the tls_setup() function. 

However, since port_setup runs after tls_setup I think the port=0 definition from tls_setup is being overriden by port setup.

**Comment by Leo791** [comment]
And also in the entrypoint for redis I think the TLS setup is not right either:

```
if [[ "${SETUP_MODE}" == "cluster" ]]; then
            {
                echo tls-replication yes
                echo tls-cluster yes
            } >> /etc/redis/redis.conf
```

The tls-replication yes should be in an else I believe.

**Comment by drivebyer** [comment]
Thank you for pointing it out. The first issue has been fixed by #81

**Comment by Leo791** [comment]
> Thank you for pointing it out. The first issue has been fixed by #81

Thank you, do you know when a new image will be issued with this fix?

**Comment by drivebyer** [comment]
> Thank you, do you know when a new image will be issued with this fix?

Sorry, I'm not sure about the exact time.

**Comment by drivebyer** [comment]
You can try the latest v6.2.14 v7.0.15 @Leo791
